#!/usr/bin/python3

""" This module factorizes as many numbers as possible into a product
of two smaller numbers"""

import sys
import math

def factorize(number):
    """It returns the factorized numbers"""
    for i in range(2, (int(math.sqrt(number)) + 1)):
        if number % i == 0:
            return i, number // i

def main(filename):
    """accesses and reads a file"""
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize(number)
            print("{}={}*{}".format(number, factors[1], factors[0]))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)
